### ISSUE TITLE
Pending tasks for Inference v4.1

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#177]
- [x] mlcommons/cm4mlperf-inference#4
- [ ] mlcommons/cm4mlops#176
- [ ] mlcommons/cm4mlops#175
- [ ] mlcommons/cm4mlops#174
- [ ] mlcommons/cm4mlops#170
- [ ] mlcommons/cm4mlops#173
- [ ] mlcommons/cm4mlops#172
- [ ] mlcommons/cm4mlops#168
- [ ] mlcommons/cm4mlops#169
- [ ] mlcommons/cm4mlops#171
- [ ] mlcommons/cm4mlperf-inference#3
